ALTER TABLE anchor_user_course MODIFY COLUMN userid BIGINT(10) NOT NULL;
ALTER TABLE anchor_user_course ADD COLUMN id BIGINT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE anchor_student_course MODIFY COLUMN studentid BIGINT(10) NOT NULL;
ALTER TABLE anchor_student_course ADD COLUMN id BIGINT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY;