--------------------------------------------------------
--  File created - Friday-October-07-2016   
--------------------------------------------------------
-- Unable to render TABLE DDL for object MOODLE.M_COURSE_INFO with DBMS_METADATA attempting internal generator.
CREATE TABLE M_COURSE_INFO 
(
  ID NUMBER(12, 0) 
, COURSE NUMBER(12, 0) DEFAULT 0 
, INFO CLOB 
, INFOFORMAT NUMBER(*, 0) DEFAULT 0 
, VALIDATETIME NUMBER(10, 0) DEFAULT 0 
, TIMECREATED NUMBER(10, 0) DEFAULT 0 
, TIMEMODIFIED NUMBER(10, 0) DEFAULT 0 
, NOTE VARCHAR2(255 BYTE) 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL 
LOB (INFO) STORE AS SYS_LOB0000101266C00003$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE SYSTEM 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    FREELISTS 1 
    FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT 
  )  
)
