CREATE TABLE mdl_course_info(
id BIGINT( 10 ) AUTO_INCREMENT PRIMARY KEY ,
course BIGINT( 10 ) NOT NULL DEFAULT 0,
info LONGTEXT,
infoformat SMALLINT(4) NOT NULL DEFAULT 0,
validatetime BIGINT( 10 ) DEFAULT 0,
timecreated BIGINT(10) NOT NULL DEFAULT 0,
timecreated BIGINT(10) NOT NULL DEFAULT 0,
note VARCHAR( 255 )
)
