CREATE TABLE slide_storage (
id BIGINT(10) AUTO_INCREMENT NOT NULL PRIMARY KEY,
userid BIGINT(10) NOT NULL,
filename VARCHAR(255) NOT NULL,
content TEXT,
ctime DATETIME DEFAULT 0,
mtime DATATIME DEFAULT 0
)
